### PR TITLE
Add Sinhala language support 

### PR DESCRIPTION
**Pull request by ranganath42**
Add Sinhala language support.

### CODE REVIEW

**Comment by pemistahl** [comment]
Hello Ranganath,

thank you very much for this language addition. There are merge conflicts, unfortunately. Can you please update your PR by merging the most current state of the main branch into your feature branch? Then please generate the accuracy reports again. This should resolve the conflict. Thank you.

**Comment by ranganath42** [comment]
Done. Greate package, thanks.
About the ACCURACY_PLOTS.md and ACCURACY_TABLE.md files. Should they be edited manually? I didn't update them.

**Comment by pemistahl** [comment]
> About the ACCURACY_PLOTS.md and ACCURACY_TABLE.md files. Should they be edited manually? I didn't update them.

These files are generated by Python scripts which are stored in the [repository of Lingua's Kotlin implementation](https://github.com/pemistahl/lingua/tree/main/src/python-scripts). I will have to find a better place for those, perhaps it makes sense to move them to their own repository. I will re-generate these files myself.

As far as the merge conflicts are concerned, it seems that they cannot be resolved automatically. I will do it manually as soon as I find the time.

**Comment by ranganath42** [comment]
Hmm. I thought I did resolve the conflicts earlier. I'll have a look

**Pull request merged**
